In [1]:
import numpy as np   #scientific relations
#faster and smaller allocations than lists
#if data types are different, numpy array convert whole elements to same type
#pandas and numpy are complementary
#.reshape(1,-1)  -> row vector
#.reshape(-1,1)  -> colummn vector

In [17]:
a = np.array([1, 2, 3, 4])
a = np.array((1,2,3,4))    #both usage are true

In [3]:
a

array([1, 2, 3, 4])

In [19]:
a=([])    #an empty numpy array

In [21]:
a=np.array([3,4,5.2,7.2,9],dtype="int32")   #int32, float64 indicates that elements
#refers to the space these variables occupy in memory.

In [ ]:
a.astype(np.float32)   #If we want to convert the data type of an existing array

In [4]:
list = [10, 20, 30, 40]

In [5]:
list

[10, 20, 30, 40]

In [6]:
b = np.array(list)   #creating a numpy array in a different way

In [7]:
b

array([10, 20, 30, 40])

In [8]:
type(a)

numpy.ndarray

In [9]:
type(list)

list

In [13]:
#lists
x=[1,2,3,4]
y=[5,6,7,8]
list=[]
for i in range(len(x)):
    list.append(x[i]*y[i])
print(list)

[5, 12, 21, 32]


In [15]:
#numpy arrays
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
print(x*y)

[ 5 12 21 32]


In [10]:
t1 = (7, 8, 9)    #a tuple

In [12]:
t = np.array(t1)    #creating a numpy array in a different way

In [14]:
type(t)

numpy.ndarray

In [17]:
for i in t:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [2]:
s = np.array([1,  2, 3.5, 4.6, 7.8])

In [3]:
s

array([1. , 2. , 3.5, 4.6, 7.8])

In [26]:
for i in s:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [27]:
np.zeros(10)    #creating a numpy array consist of zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones(6, dtype="int16")

array([1, 1, 1, 1, 1, 1], dtype=int16)

In [32]:
np.full(8,5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [36]:
np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(0 ,20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
np.arange(0, 3, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [44]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [46]:
np.random.rand(5)   #gives a random value between 0-1

array([0.25368498, 0.25703975, 0.22059376, 0.24224167, 0.53832071])

In [26]:
np.random.randint(0,10, 3)   #from 0 to 10 produce numbers three by tree

array([8, 3, 1])

In [24]:
np.random.randint(0,10, (3,4))

array([[4, 7, 9, 5],
       [3, 0, 8, 9],
       [1, 9, 6, 5]])

In [28]:
m = np.random.randint(1, 10, size=10)

In [29]:
m

array([7, 9, 8, 4, 6, 4, 3, 5, 3, 4])

In [60]:
m.ndim

1

In [30]:
n = np.random.randint(0,10, (3,4))

In [31]:
n

array([[4, 2, 6, 2],
       [6, 1, 3, 4],
       [1, 0, 0, 0]])

In [32]:
n.ndim    #dimensions

2

In [33]:
n.shape   #shape

(3, 4)

In [61]:
n.size    #count of elements

12

In [62]:
n.dtype

dtype('int32')

In [34]:
x = np.array([1,2,3])
y = x.reshape(1,3)    #1 row 3 column

In [35]:
y    #two dimensional matrix 

array([[1, 2, 3]])

In [72]:
k = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
k.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [84]:
np.concatenate([a1,a2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
b1 = np.array([[1, 2, 3], [4, 5, 6]]) 
b2 = np.array([10, 20, 30])

In [37]:
b1

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
b2

array([10, 20, 30])

In [39]:
np.vstack([b1, b2])     #vertical concat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [92]:
c1 = np.array([[1, 2, 3], [4, 5, 6]])
c2 = np.array([[7,8], [10, 20]])
               

In [93]:
np.hstack([c1, c2])     #horizontal concat

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6, 10, 20]])

In [126]:
z = np.random.randint(1, 20, 12)

In [127]:
z

array([ 7, 17, 19,  9, 13,  3,  6,  6,  2, 13,  3,  7])

In [98]:
np.split(z, [5])

[array([10,  7,  8,  9, 19]), array([19,  3,  4, 13, 13,  7,  5])]

In [99]:
np.split(z, [5,7])

[array([10,  7,  8,  9, 19]), array([19,  3]), array([ 4, 13, 13,  7,  5])]

In [100]:
p = np.random.randint(12, size=(3,4))

In [101]:
p

array([[ 8,  2, 11,  9],
       [ 6,  6,  4,  9],
       [ 0, 11,  4,  5]])

In [102]:
p[1,1]   #rows first and then columns

6

In [104]:
p = np.random.randint(20, size=(5,4))

In [106]:
p

array([[ 3,  7,  8, 13],
       [11,  2,  0, 17],
       [ 6,  0, 19,  5],
       [18,  4,  0,  4],
       [ 8,  4, 15, 17]])

In [107]:
p[2,1:]    #row: 2    column: take all elements after 1

array([ 0, 19,  5])

In [108]:
p = np.random.randint(50, size=(10,5))

In [109]:
p

array([[38, 34, 44, 10, 36],
       [21,  1,  5, 44, 25],
       [22, 25,  2, 10,  8],
       [36,  9, 29, 13, 30],
       [13, 44,  1, 34,  5],
       [ 7, 46, 34, 17, 10],
       [40,  3,  9, 28, 30],
       [ 2, 43, 31, 11,  3],
       [12, 48,  1, 19,  5],
       [14, 26, 24, 28,  3]])

In [111]:
p[4:6, 1:3]    #first value include, last value exclude

array([[44,  1],
       [46, 34]])

In [115]:
list1 = [1, 2, 3, 4, 5]

In [116]:
list2 = list1

In [117]:
list1

[1, 2, 3, 4, 5]

In [118]:
list2

[1, 2, 3, 4, 5]

In [119]:
list1[2]=10

In [120]:
list1

[1, 2, 10, 4, 5]

In [121]:
list2

[1, 2, 10, 4, 5]

In [43]:
import pandas as pd
#1D -> Series
#2D -> Data Frames

In [132]:
pd.Series([1, 2, 3, 4, 5, 6])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [136]:
seri = pd.Series(["Ankara", "İstanbul", "Bursa", "Antalya"])

In [137]:
seri

0      Ankara
1    İstanbul
2       Bursa
3     Antalya
dtype: object

In [138]:
list = [4, 5, 6, 7, 8, 9]
seri = pd.Series(list)     #create pandas series in a different way

In [139]:
seri

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64

In [140]:
type(seri)

pandas.core.series.Series

In [141]:
seri.dtype

dtype('int64')

In [142]:
seri.values

array([4, 5, 6, 7, 8, 9], dtype=int64)

In [143]:
seri.size     #element count

6

In [145]:
seri.head()

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [146]:
seri.head(3)

0    4
1    5
2    6
dtype: int64

In [147]:
seri.tail()

1    5
2    6
3    7
4    8
5    9
dtype: int64

In [148]:
seri.tail(4)

2    6
3    7
4    8
5    9
dtype: int64

In [150]:
seri[3]

7

In [44]:
a=np.arange(1,6)
seri=pd.Series(a)    #create a seri from a numpy array

In [45]:
a

array([1, 2, 3, 4, 5])

In [46]:
seri2 = pd.Series((1, 2, 3, 4, 5), index=("a", "b", "c", "d", "e"))   #change a index value

In [47]:
seri2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [49]:
seri2["c"]

3

In [161]:
dict = {"a":1, "b":2, "c":3, "d":4}

In [162]:
dict

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [163]:
seri = pd.Series(dict)   #creating a seri from dictionaries

In [164]:
seri

a    1
b    2
c    3
d    4
dtype: int64

In [165]:
seri.values

array([1, 2, 3, 4], dtype=int64)

In [166]:
seri.items  

<bound method Series.items of a    1
b    2
c    3
d    4
dtype: int64>

In [167]:
seri.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [168]:
seri2 = pd.Series((1, 2, 3, 4, 5), index=("a", "b", "c", "d", "e"))

In [169]:
seri[1:4]

b    2
c    3
d    4
dtype: int64

In [170]:
seri3 = pd.Series((1, 2, 3, 4), index=("a", "b", "c", "d"))

In [171]:
seri4 = seri2 = pd.Series((10, 20, 30, 40), index=("f", "g", "h", "j"))

In [172]:
pd.concat([seri3, seri4])

a     1
b     2
c     3
d     4
f    10
g    20
h    30
j    40
dtype: int64

In [4]:
import pandas as pd

In [3]:
seri4 = pd.Series((1, 2, 3, 4), index=("a", "b", "c", "d"))

In [4]:
seri4

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
#If we change the index values in the series with different numerical expressions, a null value is returned when we want to perform the slicing operation.
a = pd.Series([1, 2, 3, 4, 5, 6])
a.index=(10,20,30,40,50,60)
a[10:50]

Series([], dtype: int64)

In [6]:
a.loc[10:30]

10    1
20    2
30    3
dtype: int64

In [ ]:
# The iloc method does the exact opposite of the loc method. 
# If we want to reach the elements of the series without taking into account the index values we give,

In [178]:
seri4.iloc[1:4]         #index location

b    2
c    3
d    4
dtype: int64

In [183]:
(seri4>3) & (seri4<5)

a    False
b    False
c    False
d     True
dtype: bool

In [184]:
seri4.loc["a":"d"] 

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
data = pd.read_csv("titanic_train.csv")   

In [ ]:
len(data)

In [186]:
x = np.arange(1,16).reshape(5,3)

In [187]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [188]:
pd.DataFrame(x, columns=["s1", "s2", "s3"])

s1  s2  s3
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

In [189]:
dict = {"column": {"s1":1, "s2":2, "s3":3, "s4":4}}

In [190]:
pd.DataFrame(dict)

column
s1       1
s2       2
s3       3
s4       4

In [8]:
dict = {"column1": {"s1":1, "s2":2, "s3":3, "s4":4},
       "column2": {"s1":5, "s2":6, "s3":7, "s4":8},
       "column3": {"s1":9, "s2":10, "s3":11, "s4":12}}

In [9]:
data1 = pd.DataFrame(dict)

In [10]:
data1

column1  column2  column3
s1        1        5        9
s2        2        6       10
s3        3        7       11
s4        4        8       12

In [11]:
data1.iloc[0:2, 2]

s1     9
s2    10
Name: column3, dtype: int64

In [12]:
data1

column1  column2  column3
s1        1        5        9
s2        2        6       10
s3        3        7       11
s4        4        8       12

In [15]:
data1.drop("column1", axis=1, inplace=True)     #inplace=True -> save to the dataframe
#axis=0 -> row
#axis=1 -> column

In [16]:
data1

column2  column3
s1        5        9
s2        6       10
s3        7       11
s4        8       12

In [60]:
data1["column4"]= (33, 56, 22, 54)

In [61]:
data1

column2  column3  column4
s1        5        9       33
s2        6       10       56
s3        7       11       22
s4        8       12       54