In [2]:
import numpy as np
import pandas as pd
import os
import PIL.Image as img

In [17]:
bacterial_leaf_blight="rice_leaf_diseases/Bacterial leaf blight"
brown_spot="rice_leaf_diseases/Brown spot"
leaf_smut="rice_leaf_diseases/Leaf smut"
test="rice_leaf_diseases/test/test.png"

In [4]:
def file(path):
    return [os.path.join(path,f) for f in os.listdir(path)]    # enters the folder from the path entered as a parameter, reads all folders inside and returns the name of each folder

In [5]:
def convert_data(file_name, class_name):
    photos=file(file_name)
    photo_class=[]
    
    for photo in photos:   
        read_photo = img.open(photo).convert("L")    #grayscale -> decreasing efficiency on colour images
        resize_photo = read_photo.resize((28,28))  #for second bracket is in tuple format, resize the photo by 28x28
        normalize_photo = np.array(resize_photo)/255.0  #There are 255 values in total, since the photo is coloured, we actually scale the photo between 0-255 -> increases efficiency and learning
        convert_photo=normalize_photo.flatten()  
        
        if class_name == "bacterial_leaf_blight":
            data = np.append(convert_photo, [0])  
        elif class_name == "brown_spot":
            data = np.append(convert_photo, [1])   
        elif class_name == "leaf_smut":
            data = np.append(convert_photo, [2])
        else:
            continue
        
        photo_class.append(data)
    return photo_class
        

In [6]:
data_bacterial_leaf_blight = convert_data(bacterial_leaf_blight, "bacterial_leaf_blight")    #We created two dataframes named covid and non-covid and in the last column it returns its class, if he/she is covid it writes 1, is not 0
bacterial_leaf_blight_df = pd.DataFrame(data_bacterial_leaf_blight)
data_brown_spot = convert_data(brown_spot, "brown_spot")
brown_spot_df = pd.DataFrame(data_brown_spot)
data_leaf_smut = convert_data(leaf_smut, "leaf_smut")
leaf_smut_df = pd.DataFrame(data_leaf_smut)

In [7]:
all_data = pd.concat([bacterial_leaf_blight_df, brown_spot_df, leaf_smut_df])

In [8]:
all_data

0         1         2         3         4         5         6    \
0   0.850980  0.850980  0.850980  0.850980  0.850980  0.854902  0.850980   
1   0.850980  0.850980  0.847059  0.847059  0.847059  0.843137  0.839216   
2   0.878431  0.874510  0.874510  0.874510  0.874510  0.874510  0.878431   
3   0.898039  0.894118  0.898039  0.894118  0.894118  0.894118  0.894118   
4   0.913725  0.913725  0.917647  0.917647  0.917647  0.917647  0.921569   
..       ...       ...       ...       ...       ...       ...       ...   
34  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
35  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
36  0.035294  0.039216  0.039216  0.039216  0.039216  0.039216  0.039216   
37  0.027451  0.031373  0.031373  0.031373  0.031373  0.031373  0.031373   
38  0.400000  0.435294  0.427451  0.396078  0.356863  0.368627  0.356863   

         7         8         9    ...       775       776       777       778  \
0   0.850980  0.850980  0.847059  ...  0.843137  0.847059  0.847059  0.850980   
1   0.843137  0.843137  0.843137  ...  0.850980  0.854902  0.854902  0.858824   
2   0.878431  0.878431  0.882353  ...  0.890196  0.886275  0.886275  0.886275   
3   0.894118  0.890196  0.894118  ...  0.870588  0.866667  0.870588  0.866667   
4   0.921569  0.921569  0.921569  ...  0.921569  0.921569  0.921569  0.921569   
..       ...       ...       ...  ...       ...       ...       ...       ...   
34  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
35  1.000000  1.000000  1.000000  ...  0.952941  0.952941  0.952941  0.952941   
36  0.039216  0.039216  0.039216  ...  0.031373  0.031373  0.031373  0.027451   
37  0.031373  0.031373  0.031373  ...  0.039216  0.039216  0.039216  0.039216   
38  0.305882  0.282353  0.317647  ...  1.000000  1.000000  1.000000  1.000000   

         779       780       781       782       783  784  
0   0.850980  0.850980  0.850980  0.850980  0.854902  0.0  
1   0.858824  0.858824  0.858824  0.858824  0.862745  0.0  
2   0.886275  0.886275  0.882353  0.882353  0.882353  0.0  
3   0.866667  0.862745  0.858824  0.858824  0.854902  0.0  
4   0.917647  0.917647  0.917647  0.913725  0.913725  0.0  
..       ...       ...       ...       ...       ...  ...  
34  1.000000  1.000000  1.000000  1.000000  1.000000  2.0  
35  0.952941  0.952941  0.952941  0.952941  0.952941  2.0  
36  0.031373  0.027451  0.027451  0.027451  0.027451  2.0  
37  0.039216  0.039216  0.039216  0.039216  0.039216  2.0  
38  1.000000  1.000000  1.000000  1.000000  1.000000  2.0  

[119 rows x 785 columns]

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [10]:
input = np.array(all_data)[: , :784]
output = np.array(all_data)[: , 784]

In [11]:
input_train, input_test, output_train, output_test = train_test_split(input, output, test_size=0.2, random_state=42)
model = DecisionTreeClassifier(max_depth=1)  
clf=model.fit(input_train, output_train)
output_pred=clf.predict(input_test)
print("accuracy: ", metrics.accuracy_score(output_test,output_pred))

accuracy:  0.4583333333333333


In [18]:
read_photo1 = img.open(test).convert("L")                                                                                                                                          
resize_photo1 = read_photo1.resize((28,28))  
normalize_photo1 = np.array(resize_photo1)/255.0  
convert_photo1=normalize_photo1.flatten()   
convert_photo1=np.reshape(convert_photo1, (1,-1))

print(clf.predict(convert_photo1))

if clf.predict(convert_photo1) == 0:
    text = "bacterial leaf blight.."
    print(text)
elif clf.predict(convert_photo1) == 1:
    text = "brown spot.."
    print(text)
elif clf.predict(convert_photo1) == 2:
    text = "leaf smut.."
    print(text)
    

[1.]
brown spot..


In [19]:
import cv2
photo=cv2.imread(test)
cv2.putText(photo, text, (10,230), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,100,155),2)  
cv2.imshow("tahmin", photo)
cv2.waitKey(5)   
cv2.destroyAllWindows

<function destroyAllWindows>

In [20]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(output_test, output_pred)
print(cm)  

[[5 2 0]
 [2 6 0]
 [4 5 0]]


: 